export const achievements = [
  {
    imgURL:      "/demoPhoto/5.jpg",
    date:        "10 March, 2026",
    isoDate:     "2026-03-10",
    title:       "RUET CSE Ranks Among Top 5 Engineering Departments in Bangladesh 2026",
    description: "The Department of Computer Science & Engineering at RUET has been ranked among the top five engineering departments in Bangladesh by the National Academic Excellence Council. The ranking evaluated research output, graduate employment rates, industry collaboration, and student satisfaction scores over a three-year period.",
  },
  {
    imgURL:      "/demoPhoto/6.jpg",
    date:        "20 February, 2026",
    isoDate:     "2026-02-20",
    title:       "Two RUET CSE Faculty Members Receive National Research Excellence Award",
    description: "Dr. Mahmudul Hasan and Dr. Farzana Islam of the CSE department were honored with the National Research Excellence Award for their outstanding contributions to applied machine learning and network security research. The awards were presented at the Annual Academic Achievement Gala organized by the Bangladesh Research Foundation.",
  },
  {
    imgURL:      "/demoPhoto/1.webp",
    date:        "05 January, 2026",
    isoDate:     "2026-01-05",
    title:       "RUET Team Wins Gold at International Collegiate Robotics Championship",
    description: "A team of four CSE undergraduates represented RUET at the International Collegiate Robotics Championship held in Seoul, South Korea, and returned with the Gold Medal in the Autonomous Navigation category. The team's robot demonstrated exceptional precision and adaptability in dynamic obstacle environments, impressing judges from 23 participating nations.",
  },
  {
    imgURL:      "/demoPhoto/20.png",
    date:        "15 December, 2025",
    isoDate:     "2025-12-15",
    title:       "PhD Student Publishes Research in Nature Scientific Reports",
    description: "Md. Rafiur Rahman, a PhD candidate in the CSE department, published a first-author research paper in Nature Scientific Reports, one of the world's most respected multidisciplinary journals. The paper presents a novel graph neural network architecture for early detection of anomalous patterns in large-scale network traffic data.",
  },
  {
    imgURL:      "/demoPhoto/3.webp",
    date:        "02 November, 2025",
    isoDate:     "2025-11-02",
    title:       "RUET CSE Secures Government Grant for Quantum Computing Research",
    description: "The department has been awarded a prestigious government research grant worth BDT 1.2 crore to establish a Quantum Computing Research Initiative. The three-year project will focus on quantum algorithm development and its application to cryptography and optimization problems, with outcomes expected to inform national digital security policy.",
  },
  {
    imgURL:      "/demoPhoto/2.webp",
    date:        "18 September, 2025",
    isoDate:     "2025-09-18",
    title:       "Students Win First Place at NASA Space Apps Challenge — Dhaka Hub",
    description: "A group of RUET CSE students captured first place at the NASA International Space Apps Challenge, Dhaka Hub, with their project on satellite imagery analysis for flood prediction using convolutional neural networks. The team advanced to the global judging round, representing Bangladesh among the top 40 projects worldwide.",
  },
  {
    imgURL:      "/demoPhoto/4.webp",
    date:        "07 August, 2025",
    isoDate:     "2025-08-07",
    title:       "RUET CSE Alumnus Named CTO of Leading Dhaka-Based Tech Startup",
    description: "Tanvir Ahmed, a 2018 graduate of the CSE department, has been appointed Chief Technology Officer at DataSpark BD, one of Bangladesh's fastest-growing technology startups. Tanvir credited RUET's rigorous curriculum and project-based learning environment for equipping him with the technical and leadership skills required for the role.",
  },
  {
    imgURL:      "/demoPhoto/12.jpg",
    date:        "22 June, 2025",
    isoDate:     "2025-06-22",
    title:       "Department Receives Accreditation from Bangladesh Accreditation Council",
    description: "The CSE department has successfully received full program accreditation from the Bangladesh Accreditation Council (BAC) following a comprehensive review of its academic programs, faculty qualifications, research facilities, and student outcomes. This accreditation affirms the department's commitment to international quality standards in engineering education.",
  },
  {
    imgURL:      "/demoPhoto/13.jpg",
    date:        "10 April, 2025",
    isoDate:     "2025-04-10",
    title:       "Undergraduate Team Wins National Hackathon — Digital Bangladesh Innovate 2025",
    description: "A four-member undergraduate team from RUET CSE won the grand prize at the National Hackathon: Digital Bangladesh Innovate 2025. Their project, an AI-powered rural healthcare triage system, was selected from over 300 competing teams. The solution is being piloted in collaboration with a district health authority in Rajshahi.",
  },
  {
    imgURL:      "/demoPhoto/14.jpg",
    date:        "15 February, 2025",
    isoDate:     "2025-02-15",
    title:       "RUET CSE Faculty Delivers Keynote at ACM SIGCSE International Symposium",
    description: "Professor Dr. Nasrin Sultana was invited to deliver the keynote address at the ACM Special Interest Group on Computer Science Education International Symposium. Her talk on competency-based curriculum design for AI literacy in undergraduate programs received widespread acclaim and has been highlighted in the ACM Education blog.",
  },
  {
    imgURL:      "/demoPhoto/15.jpg",
    date:        "30 January, 2025",
    isoDate:     "2025-01-30",
    title:       "RUET Students Place in Top 10 at Google Solution Challenge South Asia",
    description: "Two student teams from the RUET CSE Google Developer Student Club placed in the Top 10 at the Google Solution Challenge, South Asia Region. Their solutions — a multilingual accessibility app and a crop disease detection platform — were developed over six weeks and evaluated by a Google engineering panel.",
  },
  {
    imgURL:      "/demoPhoto/16.jpg",
    date:        "05 December, 2024",
    isoDate:     "2024-12-05",
    title:       "Research Lab Hosts First International Visiting Scholar from TU Delft",
    description: "The CSE Research Lab welcomed its first international visiting scholar, Dr. Lena Müller from Delft University of Technology, Netherlands, for a three-month collaborative research residency. Her work with department faculty on distributed sensor networks has resulted in two joint conference submissions and has laid the groundwork for a formal research exchange program.",
  },
]