export const mouCollaborations = [
  {
    imgURL:      "/demoPhoto/12.jpg",
    date:        "22 January, 2026",
    isoDate:     "2026-01-22",
    title:       "Academic MOU with Khulna University of Engineering & Technology — Joint Research",
    description: "RUET CSE formalized an academic MOU with KUET's CSE department to enable joint research initiatives, faculty exchange, and co-publication of scholarly work. The agreement also opens pathways for students from both institutions to participate in each other's workshops, seminars, and academic competitions.",
  },
  {
    imgURL:      "/demoPhoto/14.jpg",
    date:        "18 November, 2025",
    isoDate:     "2025-11-18",
    title:       "MOU with TechnoNext — AI Research Lab and Co-Supervised Graduate Projects",
    description: "TechnoNext Software Limited and RUET CSE signed an MOU establishing a jointly funded AI Research Lab on campus. The lab will support co-supervised graduate projects, with TechnoNext engineers serving as industry co-supervisors for selected MSc and PhD dissertations. A joint publication program has also been agreed upon as part of the arrangement.",
  },
  {
    imgURL:      "/demoPhoto/15.jpg",
    date:        "30 October, 2025",
    isoDate:     "2025-10-30",
    title:       "Agreement with Grameenphone — IoT Research Collaboration and Network Testbed Access",
    description: "Grameenphone Ltd. and RUET CSE announced a research collaboration agreement focused on Internet of Things applications and next-generation network technologies. Under the agreement, Grameenphone will provide access to a live network testbed for faculty and graduate researchers, along with co-funding for selected IoT research projects.",
  },
  {
    imgURL:      "/demoPhoto/16.jpg",
    date:        "01 March, 2026",
    isoDate:     "2026-03-01",
    title:       "MOU Signed with Brain Station 23 for Research Collaboration and Internship Program",
    description: "The CSE Department signed a Memorandum of Understanding with Brain Station 23, one of Bangladesh's largest software companies, to establish a structured research collaboration and internship pipeline. The agreement covers co-supervised capstone projects, sponsored research on agile software development, and preferential hiring pathways for RUET CSE graduates.",
  },
  {
    imgURL:      "/demoPhoto/2.webp",
    date:        "14 February, 2026",
    isoDate:     "2026-02-14",
    title:       "Partnership with BJIT Group — Scholarship and Fast-Track Placement Agreement",
    description: "RUET CSE and BJIT Group formalized a partnership agreement that includes a merit scholarship scheme for undergraduate students and a fast-track placement program for final-year graduates. BJIT engineers will also deliver guest lectures and mentor students on industry-relevant technologies throughout the academic year.",
  },
  {
    imgURL:      "/demoPhoto/3.webp",
    date:        "22 January, 2026",
    isoDate:     "2026-01-22",
    title:       "Academic MOU with Khulna University of Engineering & Technology — Joint Research",
    description: "RUET CSE formalized an academic MOU with KUET's CSE department to enable joint research initiatives, faculty exchange, and co-publication of scholarly work. The agreement also opens pathways for students from both institutions to participate in each other's workshops, seminars, and academic competitions.",
  },
  {
    imgURL:      "/demoPhoto/4.webp",
    date:        "08 December, 2025",
    isoDate:     "2025-12-08",
    title:       "Collaboration with ICT Division, Government of Bangladesh — Digital Skills Initiative",
    description: "The department entered into a formal collaboration with the ICT Division of the Government of Bangladesh to contribute to the national Digital Skills Development Initiative. The partnership involves curriculum advisory services, the development of online learning modules, and participation in government-sponsored AI and data science training programs across the country.",
  },
  {
    imgURL:      "/demoPhoto/5.jpg",
    date:        "18 November, 2025",
    isoDate:     "2025-11-18",
    title:       "MOU with TechnoNext — AI Research Lab and Co-Supervised Graduate Projects",
    description: "TechnoNext Software Limited and RUET CSE signed an MOU establishing a jointly funded AI Research Lab on campus. The lab will support co-supervised graduate projects, with TechnoNext engineers serving as industry co-supervisors for selected MSc and PhD dissertations. A joint publication program has also been agreed upon as part of the arrangement.",
  },
  {
    imgURL:      "/demoPhoto/6.jpg",
    date:        "30 October, 2025",
    isoDate:     "2025-10-30",
    title:       "Agreement with Grameenphone — IoT Research Collaboration and Network Testbed Access",
    description: "Grameenphone Ltd. and RUET CSE announced a research collaboration agreement focused on Internet of Things applications and next-generation network technologies. Under the agreement, Grameenphone will provide access to a live network testbed for faculty and graduate researchers, along with co-funding for selected IoT research projects.",
  },
  {
    imgURL:      "/demoPhoto/7.jpg",
    date:        "15 September, 2025",
    isoDate:     "2025-09-15",
    title:       "MOU Signed with BUET CSE — Collaborative PhD Supervision Program",
    description: "RUET and BUET's CSE departments signed a collaboration agreement to launch a joint PhD supervision program, allowing doctoral students to benefit from expertise at both institutions. The program includes co-advisor arrangements, shared access to specialized research facilities, and joint paper authorship for participating students.",
  },
  {
    imgURL:      "/demoPhoto/8.jpg",
    date:        "28 August, 2025",
    isoDate:     "2025-08-28",
    title:       "Partnership with Genex Infosys — Industry Mentorship and Live Project Access",
    description: "Genex Infosys Limited signed an MOU with RUET CSE to provide students with access to live industry projects and an industry mentorship program. Selected students will work on real client deliverables under the guidance of Genex engineers, providing hands-on experience that bridges the gap between classroom learning and professional practice.",
  },
  {
    imgURL:      "/demoPhoto/9.jpg",
    date:        "10 July, 2025",
    isoDate:     "2025-07-10",
    title:       "Research MOU with University of Helsinki — Machine Learning Exchange Program",
    description: "RUET CSE signed a research MOU with the University of Helsinki, Finland, for a bilateral machine learning research exchange program. The agreement facilitates short-term research visits for graduate students and faculty, co-organization of international workshops, and collaborative grant applications to European research funding bodies.",
  },
  {
    imgURL:      "/demoPhoto/10.jpg",
    date:        "22 May, 2025",
    isoDate:     "2025-05-22",
    title:       "Collaboration with BRAC University — Undergraduate Curriculum Joint Review",
    description: "RUET CSE and BRAC University initiated a formal curriculum collaboration to jointly review and align undergraduate CSE programs with ACM/IEEE computing curriculum guidelines. The initiative includes faculty exchange for course delivery, shared lab resources, and a biannual curriculum review workshop involving academic and industry stakeholders.",
  },
  {
    imgURL:      "/demoPhoto/11.jpg",
    date:        "08 April, 2025",
    isoDate:     "2025-04-08",
    title:       "MOU with Samsung R&D Institute Bangladesh — Innovation Lab and Talent Pipeline",
    description: "Samsung R&D Institute Bangladesh signed a landmark MOU with RUET CSE to establish an on-campus Innovation Lab equipped with Samsung development hardware. The agreement includes a structured talent pipeline, with Samsung conducting on-campus technical assessments and offering competitive internship placements to high-performing students each semester.",
  },
  {
    imgURL:      "/demoPhoto/20.png",
    date:        "15 February, 2025",
    isoDate:     "2025-02-15",
    title:       "Partnership with BASIS — Industry Readiness Workshops and Certification Support",
    description: "The Bangladesh Association of Software and Information Services (BASIS) and RUET CSE formalized a partnership to deliver industry readiness workshops, career development seminars, and support for students pursuing international technology certifications. BASIS representatives will participate in departmental advisory board meetings to help align academic output with industry needs.",
  },
]