export const newsEvents = [
  {
    imgURL:      "./demoPhoto/1.webp",
    date:        "15 March, 2026",
    isoDate:     "2026-03-15",
    title:       "RUET CSE Department Hosts National Undergraduate Programming Contest 2026",
    description: "The Department of Computer Science & Engineering at RUET successfully organized the National Undergraduate Programming Contest 2026, drawing participation from over 80 universities across Bangladesh. The two-day event featured algorithmic challenges, a hackathon round, and a keynote session by industry leaders on competitive programming and its role in modern software development careers.",
  },
  {
    imgURL:      "./demoPhoto/2.webp",
    date:        "02 February, 2026",
    isoDate:     "2026-02-02",
    title:       "Seminar on Artificial Intelligence and Machine Learning in Industry 4.0",
    description: "A distinguished seminar on AI and ML applications in Industry 4.0 was held at the CSE Seminar Hall. Renowned researchers and industry practitioners discussed the transformative potential of intelligent systems in manufacturing, healthcare, and logistics. Students had the opportunity to interact directly with speakers during a Q&A panel session.",
  },
  {
    imgURL:      "./demoPhoto/3.webp",
    date:        "28 January, 2026",
    isoDate:     "2026-01-28",
    title:       "CSE Fest 2026: Annual Tech Carnival Draws Over 500 Participants Nationwide",
    description: "CSE Fest 2026 was a resounding success, attracting more than 500 participants from universities across the country. The carnival featured project showcases, gaming tournaments, a startup pitch competition, and live performances. The event concluded with an award ceremony celebrating innovation and technical excellence among students.",
  },
  {
    imgURL:      "./demoPhoto/4.webp",
    date:        "10 December, 2025",
    isoDate:     "2025-12-10",
    title:       "MOU Signed with Leading IT Firms for Student Internship and Placement Program",
    description: "RUET CSE Department signed a formal Memorandum of Understanding with several prominent IT firms to facilitate structured internship and job placement programs for graduating students. The agreement covers mentorship, paid internships, and fast-track recruitment pipelines, providing students with direct access to top-tier industry opportunities.",
  },
  {
    imgURL:      "./demoPhoto/5.jpg",
    date:        "18 November, 2025",
    isoDate:     "2025-11-18",
    title:       "RUET CSE Research Team Wins Best Paper Award at IEEE International Conference",
    description: "A research team from the CSE department received the Best Paper Award at the IEEE International Conference on Computing and Intelligent Systems. Their paper on energy-efficient deep learning inference on edge devices was praised for its practical contributions and rigorous methodology. This marks the third consecutive year RUET has received recognition at this prestigious venue.",
  },
  {
    imgURL:      "./demoPhoto/6.jpg",
    date:        "05 October, 2025",
    isoDate:     "2025-10-05",
    title:       "Workshop on Cybersecurity: Ethical Hacking and Penetration Testing Fundamentals",
    description: "A two-day hands-on workshop on ethical hacking and penetration testing was conducted by certified cybersecurity professionals. Participants learned about common attack vectors, vulnerability assessment tools, and defense strategies. The workshop was particularly well-received by final-year students exploring careers in information security and network administration.",
  },
  {
    imgURL:      "./demoPhoto/7.jpg",
    date:        "22 September, 2025",
    isoDate:     "2025-09-22",
    title:       "Department Inauguration of New High-Performance Computing Lab for Graduate Research",
    description: "The department officially inaugurated a state-of-the-art High-Performance Computing Lab equipped with GPU clusters and distributed computing infrastructure. The facility is designed to support graduate-level research in machine learning, simulation, and data analytics, and will be available to faculty and postgraduate students on a scheduled-access basis.",
  },
  {
    imgURL:      "./demoPhoto/8.jpg",
    date:        "14 August, 2025",
    isoDate:     "2025-08-14",
    title:       "Alumni Talk Series: Career Paths in Software Engineering and Entrepreneurship",
    description: "The Alumni Talk Series returned with an inspiring session featuring successful RUET CSE graduates who have carved distinguished paths in software engineering and tech entrepreneurship. Alumni shared personal journeys, lessons learned, and practical advice for current students. The session was followed by a networking dinner connecting students with mentors.",
  },
  {
    imgURL:      "./demoPhoto/9.jpg",
    date:        "30 June, 2025",
    isoDate:     "2025-06-30",
    title:       "Convocation 2025: 320 CSE Graduates Receive Degrees at Annual Ceremony",
    description: "The Annual Convocation 2025 was held with great fanfare as 320 CSE graduates received their degrees. The Chief Guest delivered an inspiring address on the responsibilities of engineers in a rapidly evolving digital world. Gold medals were awarded to top performers, and the event was attended by faculty, family members, and distinguished guests.",
  },
  {
    imgURL:      "./demoPhoto/10.jpg",
    date:        "11 May, 2025",
    isoDate:     "2025-05-11",
    title:       "RUET Students Secure Top Positions in ICPC Asia Dhaka Regional Contest",
    description: "RUET CSE students delivered an outstanding performance at the ICPC Asia Dhaka Regional Contest, securing multiple top-10 finishes and qualifying for the Asia West Continent Final. The achievement highlights the department's growing strength in competitive programming, supported by dedicated coaching and regular in-house practice contests.",
  },
  {
    imgURL:      "./demoPhoto/11.jpg",
    date:        "03 April, 2025",
    isoDate:     "2025-04-03",
    title:       "International Webinar on Cloud Computing and DevOps Best Practices",
    description: "The department hosted an international webinar featuring cloud architects and DevOps engineers from North America and Europe. Topics covered included containerization with Docker and Kubernetes, CI/CD pipeline design, and cloud cost optimization strategies. The session attracted registrations from over 200 participants across South Asia.",
  },
  {
    imgURL:      "./demoPhoto/12.jpg",
    date:        "17 February, 2025",
    isoDate:     "2025-02-17",
    title:       "Guest Lecture by Google Engineer on Large Language Models and Generative AI",
    description: "A senior engineer from Google delivered a captivating guest lecture on the architecture and applications of Large Language Models and Generative AI. The talk covered transformer models, prompt engineering, responsible AI practices, and the future of human-computer interaction. Students engaged in an extended technical discussion following the lecture.",
  },
  {
    imgURL:      "./demoPhoto/13.jpg",
    date:        "28 January, 2026",
    isoDate:     "2026-01-28",
    title:       "CSE Fest 2026 Closing Ceremony and Prize Distribution",
    description: "The closing ceremony of CSE Fest 2026 was held with the distribution of prizes across all competition categories. The event recognized top performers in programming contests, project exhibitions, and design challenges. The Department Head expressed appreciation for the student volunteers and sponsors who made the event a grand success.",
  },
  {
    imgURL:      "./demoPhoto/14.jpg",
    date:        "10 December, 2025",
    isoDate:     "2025-12-10",
    title:       "Industry Partnership Summit 2025 — Expanding Collaboration Frontiers",
    description: "The Industry Partnership Summit 2025 brought together representatives from over 15 technology companies to discuss extended collaboration opportunities with the department. Agenda items included curriculum advisory input, co-supervised thesis programs, and sponsored research initiatives. Several new partnerships were formally announced at the summit.",
  },
  {
    imgURL:      "./demoPhoto/15.jpg",
    date:        "18 November, 2025",
    isoDate:     "2025-11-18",
    title:       "Research Publication Milestone: 50+ Papers in Indexed Journals in 2025",
    description: "The CSE department reached a significant milestone in 2025 with faculty and students collectively publishing more than 50 research papers in Scopus and Web of Science indexed journals. This represents a 40% increase over the previous year and reflects the department's commitment to research excellence and academic impact.",
  },
  {
    imgURL:      "./demoPhoto/18.jpg",
    date:        "10 December, 2025",
    isoDate:     "2025-12-10",
    title:       "Industry Partnership Summit 2025 — Expanding Collaboration Frontiers",
    description: "The Industry Partnership Summit 2025 brought together representatives from over 15 technology companies to discuss extended collaboration opportunities with the department. Agenda items included curriculum advisory input, co-supervised thesis programs, and sponsored research initiatives. Several new partnerships were formally announced at the summit.",
  },
  {
    imgURL:      "./demoPhoto/16.jpg",
    date:        "05 October, 2025",
    isoDate:     "2025-10-05",
    title:       "Cybersecurity Awareness Month — Poster Presentation and Quiz Competition",
    description: "In observance of Cybersecurity Awareness Month, the department organized a poster presentation competition and an inter-batch quiz contest focusing on digital safety, privacy, and ethical computing. The event aimed to cultivate a security-conscious mindset among students and faculty, with prizes awarded to the top three teams in each category.",
  },
  {
    imgURL:      "./demoPhoto/19.jpg",
    date:        "18 November, 2025",
    isoDate:     "2025-11-18",
    title:       "Research Publication Milestone: 50+ Papers in Indexed Journals in 2025",
    description: "The CSE department reached a significant milestone in 2025 with faculty and students collectively publishing more than 50 research papers in Scopus and Web of Science indexed journals. This represents a 40% increase over the previous year and reflects the department's commitment to research excellence and academic impact.",
  },
  {
    imgURL:      "./demoPhoto/20.png",
    date:        "17 February, 2025",
    isoDate:     "2025-02-17",
    title:       "Generative AI Study Circle Launch — Weekly Discussion Sessions Begin",
    description: "A student-led Generative AI Study Circle was formally launched within the department, aimed at fostering collaborative learning around the latest advancements in AI. Weekly sessions cover research papers, hands-on experiments with open-source models, and discussions on ethical implications. Faculty mentors guide the group on project ideation and publication opportunities.",
  },
  {
    imgURL:      "./demoPhoto/17.jpg",
    date:        "28 January, 2026",
    isoDate:     "2026-01-28",
    title:       "CSE Fest 2026 Closing Ceremony and Prize Distribution",
    description: "The closing ceremony of CSE Fest 2026 was held with the distribution of prizes across all competition categories. The event recognized top performers in programming contests, project exhibitions, and design challenges. The Department Head expressed appreciation for the student volunteers and sponsors who made the event a grand success.",
  },
  
]